package se.sandboge.japanese.lists;


public class CreateKanjiHtml {
    
    private static String[][] kanjis = {
            {"hus", "か、いえ", "家"},
            {"pil", "や", "矢"},
            {"familj", "ぞく", "族"},
            {"förälder, intimitet", "しん、おや", "親"},
            {"äldre bror", "きょう、あに", "兄"},
            {"äldre syster", "あね", "姉"},
            {"yngre bror", "だい、おとうと", "弟"},
            {"yngre syster", "いもうと", "妹"},
            {"jag, privat", "わたくし、わたし", "私"},
            {"man", "おっと", "夫"},
            {"fru", "つま", "妻"},
            {"huvudsaklig", "しゅ", "主"},
            {"bo", "す", "住"},
            {"tråd", "いと", "糸"},
            {"efternamn", "し", "氏"},
            {"papper", "かみ、がみ", "紙"},
            {"lära ut", "きょう、おし", "教"},
            {"rum", "しつ", "室"},
            {"vinge", "はね", "羽"},
            {"lära sig", "なら", "習"},
            {"kina", "かん", "漢"},
            {"bokstav, tecken", "じ", "字"},
            {"ceremoni", "しき", "式"},
            {"försöka", "し", "試"},
            {"undersöka", "けん", "験"},
            {"värdshus", "しゅく", "宿"},
            {"ämne", "だい", "題"},
            {"mening, tecken", "ぶん", "文"},
            {"engelska, utmärkt", "えい", "英"},
            {"kvalitet", "しつ", "質"},
            {"fråga", "もん", "問"},
            {"förklara", "せつ", "説"},
            {"långt bort", "とお", "遠"},
            {"nära", "ちか", "近"},
            {"person", "しゃ", "者"},
            {"het", "あつ", "暑"},
            {"kall", "さむ", "寒"},
            {"tung", "おも", "重"},
            {"lätt", "かる", "軽"},
            {"låg", "ひく", "低"},
            {"svag", "よわ", "弱"},
            {"dålig", "わる", "悪"},
            {"mörk", "くら", "暗"},
            {"tjock", "ふと", "太"},
            {"böna", "まめ", "豆"},
            {"kort", "みじか", "短"},
            {"ljus", "ひかり、ひか", "光"},
            {"vind", "ふう、かぜ", "風"},
            {"transportera, tur", "うん、はこ", "運"},
            {"flytta", "どう、うご", "動"},
            {"stoppa", "し、と", "止"},
            {"gå", "ある", "歩"},
            {"använda", "つか", "使"},
            {"sända", "おく", "送"},
            {"tvätta", "あら", "洗"},
            {"skynda sig", "きゅう、いそ", "急"},
            {"öppna", "あ、ひら", "開"},
            {"stänga", "し", "閉"},
            {"trycka", "お", "押"},
            {"dra", "ひ", "引"},
            {"tänka", "おも", "思"},
            {"tänka, idé", "かんが", "考"},
            {"veta", "し", "知"},
            {"död", "し", "死"},
            {"doktor, medicin", "い", "医"},
            {"börja", "はじ", "始"},
            {"sluta", "お", "終"},
            {"sten", "いし", "石"},
            {"polera", "けん", "研"},
            {"forskning", "きゅう", "究"},
            {"stanna", "りゅう", "留"},
            {"existera", "ゆう", "有"},
            {"producera", "さん", "産"},
            {"affärer", "ぎょう", "業"},
            {"medicin", "くすり", "薬"},
            {"arbeta", "はたら", "働"},
            {"medlem", "いん", "員"},
            {"samurai", "し", "士"},
            {"tjäna", "し", "仕"},
            {"sak", "じ、こと、ごと", "事"},
            {"teckning", "と、ず", "図"},
            {"ämbetsman", "かん", "官"},
            {"byggnad", "かん", "館"},
            {"urtida", "むかし", "昔"},
            {"låna", "か", "借"},
            {"tidsålder,ersätta", "だい、か", "代"},
            {"låna ut", "か", "貸"},
            {"land", "ち", "地"},
            {"värld", "せ", "世"},
            {"gräns", "かい", "界"},
            {"gånger,grader", "ど", "度"},
            {"rotera", "かい、まわ", "回"},
            {"använda", "よう", "用"},
            {"folk", "みん", "民"},
            {"hälla", "ちゅう", "注"},
            {"sinne", "い", "意"},
            {"huvud", "あたま", "頭"},
            {"ansikte", "かお", "顔"},
            {"röst", "こえ", "声"},
            {"speciell", "とく", "特"},
            {"separera", "べつ、わか", "別"},
            {"bambu", "たけ", "竹"},
            {"passa", "あ", "合"},
            {"svara", "こた", "答"},
            {"rätt", "しょう、せい、ただ", "正"},
            {"samma", "おな", "同"},
            {"mäta", "けい", "計"},
            {"huvudstad", "きょう", "京"},
            {"samla", "あつ", "集"},
            {"icke", "ふ", "不"},
            {"bekväm,post", "べん", "便"},
            {"startpunkt", "い", "以"},
            {"plats", "じょう、ば", "場"},
            {"dörr", "と", "戸"},
            {"plats", "しょ、じょ、ところ、どころ", "所"},
            {"tak,affär", "おく、や", "屋"},
            {"hall", "どう", "堂"},
            {"metropolis", "と", "都"},
            {"prefektur", "けん", "県"},
            {"zon", "く", "区"},
            {"damm", "ち、いけ", "池"},
            {"starta,avslöja", "はつ、ばつ", "発"},
            {"bygga", "た", "建"},
            {"sak", "ぶつ、もの", "物"},
            {"gods", "しな", "品"},
            {"resa", "りょ", "旅"},
            {"passera,pendla", "とお、かよ", "通"},
            {"avancera", "すす", "進"},


            {"ett", "いち、ひと", "一"},
            {"klockan", "とき、じ", "時"},
            {"stad", "し", "市"},
            {"logik", "り", "理"},
            {"skära", "せつ、き、きっ", "切"},
            {"måne,månad", "がつ、げつ、つき", "月"},
            {"upp", "うえ、あ", "上"},
            {"ner", "した、き", "下"},
            {"namn", "な", "名"},
            {"ljust", "みょう、あか、あ", "明"},
            {"liten", "しょう、ちい", "小"},
            {"utanför", "そと", "外"},
            {"ändring", "", "化"},
            {"norr", "きた、北", "北"},
            {"energi", "き", "気"},
            {"möte", "あ", "会"},
            {"födelse", "う", "生"},
            {"", "", "映"},
            {"", "", "大"},
            {"", "", "本"},
            {"", "", "中"},
            {"", "", "画"},
            {"", "", "社"},
            {"", "", "着"},
            {"", "", "手"},
            {"", "", "何"},
            {"", "", "作"},
            {"", "", "入"},
            {"", "", "学"},
            {"", "", "火"},
            {"", "", "話"},
            {"", "", "東"},
            {"", "", "味"},
            {"", "", "長"},
            {"", "", "銀"},
            {"", "", "見"},
            {"", "", "間"},
            {"", "", "首"},
            {"", "", "店"},
            {"", "", "語"},
            {"", "", "買"},
            {"", "", "人"},
            {"", "", "今"},
            {"", "", "車"},
            {"", "", "野"},
            {"", "", "食"},
            {"", "", "転"},
            {"", "", "工"},
            {"", "", "自"},
            {"", "", "台"},
            {"", "", "売"},
            {"", "", "飲"},
            {"", "", "音"},
            {"", "", "書"},
            {"", "", "出"},
            {"", "", "電"},
            {"", "", "午"},
            {"", "", "行"},
    };

    public static void main(String[] args) {
        int size = kanjis.length;
        for (int i = 0; i < size; i += 2) {
            System.out.println("<tr>");
            printCol(i);
            if (i < size - 1) {
                printCol(i+1);
            }
            System.out.println("</tr>");
        }
        System.out.println("================");
        for (String[] kanji : kanjis) {
            //     ['stor','大'],
            if (kanji[0].equals("")) continue;
            System.out.println("['" + kanji[0] + "(" + kanji[1] + ")','" + kanji[2] + "'],");
        }
    }

    private static void printCol(int x) {
        String kanjiCode = Integer.toHexString(kanjis[x][2].charAt(0));
//        <td>大</td><td>だい<br>おお</td><td>stor</td><td><object data="svg/05927.svg" type="image/svg+xml"></object></td>
//        <td>小</td><td>しょう<br>ちい</td><td>liten</td><td><object data="svg/05c0f.svg" type="image/svg+xml"></object></td>
        System.out.println("<td>" + kanjis[x][2] + "</td><td>" + kanjis[x][1] + "</td><td>" + kanjis[x][0] + "</td><td><object data=\"svg/0" + kanjiCode + ".svg\" type=\"image/svg+xml\"></object></td>");

    }
}
